<?php
    $title = "Privacy Policy";

    $privacy_policy = [
        "There are no cookies on the page, and your personal data is not stored with a database provider.",
        "Passwords generated by the application are automatically provided based on a specific library; the creator of the website has no connection to the generated passwords.",
        "The encryption library used in the application is Composer's RSA library.",
        "The generated passwords are never stored in a database."
    ];

    $company = "TrinsyCa";
    $by = "Ömer İslamoğlu";
?>

<h1 class="alertTitle"><?php echo nl2br($title); ?> <button class="closeBtn" onclick="closePrivacy();"><i class="fa-solid fa-x"></i></button></h1>
<p class="alertText">
    <?php 
        foreach($privacy_policy as $row)
        {
            echo "・".nl2br($row)."<br><br>";
        }
    ?>
</p>
<div class="alertBottom">
    <span></span>
    <div class="bigAuthor">
        <a href="https://trinsyca.bistbilisim.com" target="_blank"><?php echo nl2br($company); ?></a>
        <a href="https://bistbilisim.com/student/TrinsyCa" target="_blank"><?php echo nl2br($by); ?></a>
    </div>
</div>